# This file is designed for HTTP-only mode (no HTTPS)
# It overrides specific services from docker-compose.prod.yml

services:
  app:
    extends:
      file: docker-compose.prod.yml
      service: app

  webserver:
    extends:
      file: docker-compose.prod.yml
      service: webserver
    ports:
      - "${HTTP_PORT:-80}:${HTTP_PORT:-80}"
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-my-laravel-base-project.test}
      - HTTP_PORT=${HTTP_PORT:-80}
      - HTTP_ONLY=yes

  db:
    extends:
      file: docker-compose.prod.yml
      service: db

  mailserver:
    extends:
      file: docker-compose.prod.yml
      service: mailserver

  # Override certbot configuration to disable it in HTTP-only mode
  certbot:
    extends:
      file: docker-compose.prod.yml
      service: certbot
    profiles:
      - donotstart
    command: echo "HTTP_ONLY mode enabled, skipping SSL certificate generation"

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
  certbot-etc:
    driver: local
  certbot-var:
    driver: local
  web-root:
    driver: local
